apiVersion: v1
kind: ConfigMap
metadata:
  name: employee
  labels:
    app: employee
data:
  application.yaml: |-
    mongodb.uri: mongodb://mongodb:27017/admin
---
apiVersion: v1
kind: Secret
metadata:
  name: employee
type: Opaque
data:
  mongodb.credential.userName: UGlvdF8xMjM=
  mongodb.credential.password: cGlvdHI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: piomin/employee:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: employee
  type: NodePort