apiVersion: v1
kind: ConfigMap
metadata:
  name: department
  labels:
    app: department
data:
  application.yaml: |-
    mongodb.uri: mongodb://mongodb:27017/admin
---
apiVersion: v1
kind: Secret
metadata:
  name: department
type: Opaque
data:
  mongodb.credential.userName: UGlvdF8xMjM=
  mongodb.credential.password: cGlvdHI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: piomin/department
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: department
  labels:
    app: department
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: department
  type: NodePort